# Generated by Django 5.1.7 on 2025-03-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="thread_id",
            field=models.CharField(max_length=100),
        ),
    ]
